### PR TITLE
Fix inconsistencies in memmap() and file.seek()

### LINKED ISSUE #26: MemoryError?
This could have something to do with my hastily configured PyCharm environment, but I am running something relatively simple here:

```
datafile = 'C:/Users/pwanda/PycharmProjects/brDataParse/data/array_Sc2.ns6'
elec_ids = range(1, 96)
start_time_s = 1
data_time_s = 2
downsample_factor = 10
nsx_file = NsxFile(datafile)
cont_data = nsx_file.getdata(elec_ids, start_time_s, data_time_s)
print(cont_data['samp_per_s'])
nsx_file.close()
```

And running into this:

```
File "C:\Users\pwanda\PycharmProjects\brDataParse\elib\brpylib\brpylib.py", line 1204, in getdata
    timestamp = timestamp + (clk_per_samp * np.arange(num_data_pts)).astype(np.int64 if ts_size==8 else np.int32)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 32.0 GiB for an array with shape ([4294574184](tel:4294574184),) and data type float64
```

### PR DESCRIPTION
**Pull request by cboulay**
Fixes #26 

The bug underlying the linked issue is that when the file pointer is at the very end of the file, `file.tell()` returns `0` in Windows and the file length in *nix.

While I was debugging this, I also discovered that numpy memmap actually seeks the file pointer. I think that this _might_ be new behaviour because my previous code comments explicitly said "do a manual seek because memmap doesn't seek"... but I did something wrong during my previous testing rather than numpy changed this important feature.

I asked @cwatson-blackrock  to help with the last commit, but I'm responsible for it so we can blame any problems on me.

### CODE REVIEW

**Comment by cboulay** [comment]
Paul Wanda confirmed that this fixes his problem.

**Comment by dkluger** [comment]
@cboulay can you check on this commit? https://github.com/BlackrockNeurotech/Python-Utilities/pull/27/commits/e72eb312fcc9f4da7c2e8ad7fd128e34ad174696

Is the .ipynb file supposed to be there? If yes, is that .jpg with the crazy long png file supposed to be there?

Other commits look good

**Comment by cboulay** [comment]
Yes, the Jupyter notebook (.ipynb) is more representative of how a user would actually do a first interaction with their data including loading and plotting, which was what the previous extract_continuous_data.py script was doing. I think the .ipynb is a more useful example than the .py.

A Python script would be preferred if the task was to iterate over a bunch of files for preprocessing or training a model, but we don't currently provide any examples like that.

As for the png that's embedded in the notebook. I'm not sure how you were rendering it, but if you look at the [ipynb in GitHub](https://github.com/BlackrockNeurotech/Python-Utilities/blob/cboulay/post_ptp_fixes/examples/extract_continuous_data.ipynb) then you should see the plot. If you were looking at it in a text editor then you'd see a bunch of binary nonsense.

**Comment by dkluger** [comment]
@cboulay thanks for the insight. Never used jupyter before. The preview in Github looks better than the text!

**Review by dkluger — APPROVED** [review]
Asked about the .ipynb file that I hadn't seen before. @cboulay clarified that was a jupyter thing.

Other commits were minor and looked good on first pass. Confirmed to work from user in the field. Passes my review.

If we get flack for removing the non-Jupyter example, we can easily add it back by going through the git history.

**Comment by cboulay** [comment]
Thanks for the review!

**Pull request merged**
